###########################################################
# name=MCUE Presonus FaderPort 16 Extender
# receiveFrom=MCUE Presonus FaderPort 16
# Generated by the FIRE Place app on 26 July 2021
# For more info see https://gadgeteer.home.blog/
###########################################################
# url= https://forum.image-line.com/viewtopic.php?f=1994&t=254916#p1607888
# supportedDevices=Configured MCUE device Extenders
# Based on the ImageLine default Mackie script (refactored for the ICON QCON Pro X)
###########################################################
import math
import time

import arrangement
import channels
import device
import general
import launchMapPages
import midi
import mixer
import patterns
import playlist
import plugins
import transport
import ui
import utils

import common

MackieCU_KnobOffOnT = [(midi.MIDI_CONTROLCHANGE + (1 << 6)) << 16,
                       midi.MIDI_CONTROLCHANGE + ((0xB + (2 << 4) + (1 << 6)) << 16)]
MackieCU_nFreeTracks = 64

# -----------------
# STATIC VARIABLES
# -----------------
# Mackie CU pages
StartTime=time.time()
MackieCUPage_Pan = 0
MackieCUPage_Stereo = 1
MackieCUPage_Sends = 2
MackieCUPage_FX = 3
MackieCUPage_EQ = 4
MackieCUPage_Free = 5
MasterPeak = 0
# Standard Mackie
LCD1 =          bytearray([0xF0, 0x00, 0x00,  0x66, 0x15, 0x12, 0])  #Base Mackie Address
Ext1 =          bytearray([0xF0, 0x00, 0x00, 0x66, 0x15, 0x12, 0])  #Extender 1 Mackie Address
# QCON X Display 2
QCONX_LCD2 =    bytearray([0xF0, 0x00, 0x00, 0x67, 0x15, 0x13, 0])  #Base QCON Screen 2 Address
QCONX_Ext2 =    bytearray([0xF0, 0x00, 0x00, 0x67, 0x16, 0x13 ,0])  #Extender QCON Screen 2 Address????
# EMAGIC?
EMAGIC_LCD1 =   bytearray([0xF0, 0x00, 0x00, 0x66, 0x10, 0x12, 0])  #Base EMAGIC Mackie Address
EMAGIC_EXT =    bytearray([0xF0, 0x00, 0x00, 0x66, 0x11, 0x12, 0])  #Base EMAGIC Mackie Address

#!<
AlwaysShowSelectedTrack=False #=Track Related:=Always show me the selected track instead of the current assignment (which is probably lit up anyway!)
ShowTrackNos=True #=Track Related:=Show Track Numbers in row 2 (or longer track names if off)
SelectTrackWithBanking=False #=Track Related:=Always select the relevant track in the bank to synchronise with mixer display in FL
RouteTempTextToClassic=False #=Display Related:=Route any temporary messages to Scribble Strips / Main Display
RouteTempTextToFLDisplay=True #=Display Related:=Duplicate temporary messages to the FL Studio Hint Panel and Bar
BankNoInTimeWindow=False #=Display Related:=Always show me the current bank number in the last section of the time display
DefaultFreeDisplayToZen=False #=Free Controls:=Defaults Free control descriptions to reflect Zenology parameters
DefaultFreeDisplayToGen=True #=Free Controls:=Defaults Free control descriptions to reflect common pararmeters
TouchFaderToSelect=False #=Fader Related:=Touch a fader to select the track (can makes adjusting multiple faders at once a litle messy)
DebuggingOn=False #=General:=Developers Only (will slow down performance)
EMAGIC=False #=General:=Use for EMAGIC MCU Display Compatibility
TargetMasterMeters=False #=Enhanced Hardware:=Adds functionality for control surfaces that have a set of stereo master meters
TargetSecondDisplays=False #=Enhanced Hardware:= Provides additional information for control surfaces that have twin displays in their mixer section
FaderPortSupport = False #=Device Specific:=Some additional Support for Presonus faderport 8 and 16
CompactDescriptors = False#=Device Specific:=Tidies up some display options
SplitAccrossScribbleStrips = True#=Device Specific:=Tidies up Text accross seperate Scribble Strips
ThrottleStickSupport=False#=Device Specific:=Throttle Stock can Zoom in/out and perform various "interesting" functions
#MoreInfoURL=https://gadgeteer.home.blog/2021/04/09/dude-with-a-cool-haircut-smiley-face/
MCUELU={}


#################################
# CLASS FOR COLUMN RELATED ITEMS
#################################

class TMackieCol:
    def __init__(self):
        print('__init__')

        self.TrackNum = 0
        self.BaseEventID = 0
        self.KnobEventID = 0
        self.KnobPressEventID = 0
        self.KnobResetEventID = 0
        self.KnobResetValue = 0
        # [0=default], [1=parameter, pan, volume, off],[2=self.Flip],[3=centered?],[4=?]
        self.KnobMode = 0
        self.KnobCenter = 0
        self.SliderEventID = 0
        self.Peak = 0
        self.Tag = 0
        self.SliderName = ""
        self.KnobName = ""
        self.LastValueIndex = 0
        self.ZPeak = False
        self.Dirty = False
        self.KnobHeld = False
        #self.PrevProc="unknown"

##################################
# CLASS FOR GENERAL FUNCTIONALITY
##################################

class TMackieCU(common.TMackieCU_Base):
    def __init__(self):
        print('__init__')

        self.LastMsgLen = 0x37
        self.TempMsgT = ["", ""]
        self.LastTimeMsg = bytearray(10)
        self.Shift = False
        self.Control = False
        self.Option = False
        self.Alt = False
        self.TempMsgDirty = False
        self.JogSource = 0
        self.TempMsgCount = 0
        self.SliderHoldCount = 0
        self.FirstTrack = 9
        self.FirstTrackT = [0, 0]
        self.ColT = [0 for x in range(9)]
        for x in range(0, 9):
            self.ColT[x] = TMackieCol()
        self.FreeCtrlT = [0 for x in range(
            MackieCU_nFreeTracks - 1 + 2)]  # 64+1 sliders
        self.Clicking = False
        self.Scrub = False
        self.Flip = False
        self.MeterMode = 1  # enabled!
        self.CurMeterMode = 0
        self.Page = 0
        self.SmoothSpeed = 0
        self.MeterMax = 0
        self.ActivityMax = 0
        self.MackieCU_PageNameT = ('Panning                          (press VPOTS to reset)', 'Stereo Separation               (press VPOTS to reset)', '" - press VPOTS to enable',
                                    '" - turn VPOTS to adjust', '" - press VPOTS to reset',  '(Free Controls)')
        self.MackieCU_MeterModeNameT = ('Meters Disabled', 'Meters Enabled','+ Selected Track Shown')
        self.MackieCU_ExtenderPosT = ('left', 'right')
        self.FreeEventID = 400
        self.ArrowsStr = chr(0x7F) + chr(0x7E) + chr(0x32)
        self.AlphaTrack_SliderMax = round(13072 * 16000 / 12800)
        self.CurPluginID = -1
        self.LCD1 = bytearray([0xF0, 0x00, 0x00,  0x66, 0x15, 0x12, 0])  #Base Mackie Address
        self.LCD2 = bytearray([0xF0, 0x00, 0x00, 0x67, 0x15, 0x13, 0])  #Base QCON Screen 2 Address
        #                     [0xF0, 0x00, 0x00, 0x67, 0x15, 0x13
        self.MasterPeak = 0
        self.Msg1 = ''
        self.Msg2 = ''
        self.ShowTrackNumbers = ShowTrackNos
        if (DefaultFreeDisplayToZen):
            self.FreeText = 0  # Zenology - change to 1 (generic) or -1 (blank)
        else:
            self.FreeText = -1  # Zenology - change to 1 (generic) or -1 (blank)            
        if (DefaultFreeDisplayToGen):
            self.FreeText = 1 #Generic) or -1 (blank)
        else:
            self.FreeText = -1  # Zenology - change to 1 (generic) or -1 (blank)            
        self.colourOptions = 0
        self.ShowSelectedTrackInTimeWindow=False
        self.MixerScroll = SelectTrackWithBanking
        self.PreviousCommand=0x0
        self.LastData2=0x0
        self.PrevProc="-"


# -------------------------------------------------------------------------------------------------------------------------------
# FUNCTIONS:
# -------------------------------------------------------------------------------------------------------------------------------

    #############################################################################################################################
    #                                                                                                                           #
    # Display shortened name to fit to 7 characters (e.g., Fruity Chorus = FChorus, EQ Enhancer = EQEnhan)                      #
    #                                                                                                                           #
    #############################################################################################################################

    def DisplayName(self,name):
        print('DisplayName')

        if name == '':
            return ''

        words = name.split()
        if len(words) == 0:
            return ''

        shortName = ''

        for w in words:
            first = True
            for c in w:
                if c.isupper():
                    shortName += c
                elif first:
                    shortName += c
                else:
                    break
                first = False

        lastWord = words[len(words)-1]
        shortName += lastWord[1:]
        return shortName[0:6]

    #############################################################################################################################
    #                                                                                                                           #
    # Tidy Up Text over 8 char seperated scribble strips                                                                        #
    #                                                                                                                           #
    #############################################################################################################################

#############################################################################################################################
    #                                                                                                                           #
    # Tidy Up Text over 7 chars for seperated scribble s                                                                        #
    # ToDo: Allow for multiple words per scribble strip?                                                                        #
    #############################################################################################################################

    def TidyScribbles(self,name):
        print('TidyScribbles')

        self.PrevProc='DisplayName()'
        if name == '':
            return ''
        words = name.split()
        if len(words) == 0:
            return ''
        #tidyName = ''
        #for w in words:
        #   if not w.__contains__('-'):
        #        tidyName+=((w+' '*6)[0:7])
        s = "";
        s1=""
        n = 0;
        n1 = 1;
        words = name.split()
        while (n < len(words)):        
            if (n + 1 >= len(words)):
                n1 = 0;
            s1 = words[n] + " " + words[n + n1];
            if (len(s1)<8):
                s =s+ (s1+" "*7)[0:7];
                n = n + 2;
            else:
                s = s+ (words[n]+" "*7)[0:7];
                n=n+1
        return s
    
    #############################################################################################################################
    #                                                                                                                           #
    #  CALLED FROM UPDATECOL TO RETURN SLIDER / LEVEL VALUEDS                                                                   #
    #                                                                                                                           #
    #############################################################################################################################
    def AlphaTrack_LevelToSlider(self, Value, Max=midi.FromMIDI_Max):
        return round(Value / Max * self.AlphaTrack_SliderMax)

    #############################################################################################################################
    #                                                                                                                           #
    #  CALLED FROM UPDATECOL TO RETURN SLIDER / LEVEL VALUEDS                                                                   #
    #                                                                                                                           #
    #############################################################################################################################
    def AlphaTrack_SliderToLevel(self, Value, Max=midi.FromMIDI_Max):
        return min(round(Value / self.AlphaTrack_SliderMax * Max), Max)

# --------------------------------------------------------------------------------------------------------------------------------
# EVENTS:
# --------------------------------------------------------------------------------------------------------------------------------
    #############################################################################################################################
    #                                                                                                                           #
    #  Called when the script has been started.                                                                                 #
    #                                                                                                                           #
    #############################################################################################################################
    def OnInit(self):
        print('OnInit')

        #self.FirstTrack = 1
        self.FirstTrackT[0] = self.FirstTrack
        self.SmoothSpeed = 469
        self.Clicking = True

        device.setHasMeters()
        self.LastTimeMsg = bytearray(10)

        for m in range(0, len(self.FreeCtrlT)):
            self.FreeCtrlT[m] = 8192  # default free faders to center
        if device.isAssigned():
            device.midiOutSysex(
                bytes([0xF0, 0x00, 0x00,  0x66, 0x15, 0x0C, 1, 0xF7]))
        self.SetBackLight(2)  # backlight timeout to 2 minutes
        self.UpdateClicking()
        self.UpdateMeterMode()
        self.SetPage(self.Page)
        self.SendMsg(chr(32)*112)
        self.SendMsg2(chr(32)*112)
        ui.setHintMsg(device.getName())    
        #self.OnSendTempMsg('Linked to ' + ui.getProgTitle() + ' (' + ui.getVersion() + ')', 2000);
        self.OnSendTempMsg("MCUE script version 1.0.0            ", 2000);



    #############################################################################################################################
    #                                                                                                                           #
    #      Called before the script will be stopped.                                                                               #
    #                                                                                                                           #
    #############################################################################################################################
    def OnDeInit(self):
        print('OnDeInit')


        if device.isAssigned():
            for m in range(0, 8):
                device.midiOutSysex(
                    bytes([0xF0, 0x00, 0x00,  0x66, 0x15, 0x20, m, 0, 0xF7]))
                device.midiOutSysex(bytes(bytearray([0xd1, 0, 0xF7])))
                device.midiOutSysex(bytes(bytearray([0xd1, 16, 0xF7])))

            if ui.isClosing():
                # self.SendMsg(chr(32)*112)
                self.SendMsg( "Your MCUE script version is 1.0.0 (Please check on www.gadgeteer.home.blog for updates).   ")
                this.version
                # self.SendMsg2(chr(32)*112)
                self.SendMsg2(ui.getProgTitle() + ' session closed at ' +
                              time.ctime(time.time())+chr(32)*60, 0)
            else:
                self.SendMsg('', 1)

            self.SendAssignmentMsg('   ')

    #############################################################################################################################
    #                                                                                                                           #
    #      Called on mixer track(s) change, 'index' indicates track index of track that changed or -1 when all tracks changed.     #
    #                                                                                                                           #
    #############################################################################################################################
    def OnDirtyMixerTrack(self, SetTrackNum):
        print('OnDirtyMixerTrack')

        for m in range(0, len(self.ColT)):
            if (self.ColT[m].TrackNum == SetTrackNum) | (SetTrackNum == -1):
                self.ColT[m].Dirty = True

    #############################################################################################################################
    #                                                                                                                           #
    #  Called when something changed that the script might want to respond to.                                                  #
    #                                                                                                                           #
    #############################################################################################################################
    def OnRefresh(self, flags):
        print('OnRefresh')


        if flags & midi.HW_Dirty_Mixer_Sel:
            self.UpdateMixer_Sel()

        if flags & midi.HW_Dirty_Mixer_Display:
            self.UpdateTextDisplay()
            self.UpdateColT()

        if flags & midi.HW_Dirty_Mixer_Controls:
            for n in range(0, len(self.ColT)):
                if self.ColT[n].Dirty:
                    self.UpdateCol(n)

        # LEDs
        if flags & midi.HW_Dirty_LEDs:
            self.UpdateLEDs()



    #############################################################################################################################
    #                                                                                                                           #
    #  Called when the beat indicator has changes.                                                                              #
    #                                                                                                                           #
    #############################################################################################################################
    def OnUpdateBeatIndicator(self, Value):
        print('OnUpdateBeatIndicator')


        SyncLEDMsg = [midi.MIDI_NOTEON + (0x5E << 8), midi.MIDI_NOTEON + (
            0x5E << 8) + (0x7F << 16), midi.MIDI_NOTEON + (0x5E << 8) + (0x7F << 16)]

        if device.isAssigned():
            device.midiOutNewMsg(SyncLEDMsg[Value], 128)

    #############################################################################################################################
    #                                                                                                                           #
    #  Called when peak meters needs to be updated                                                                              #
    #                                                                                                                           #
    #############################################################################################################################
    def OnUpdateMeters(self):
        if self.CurMeterMode >= 1:
            if self.Page != MackieCUPage_Free:
                # for m in range(0, len(self.ColT) - 1):
                #    self.ColT[m].Peak = max(self.ColT[m].Peak, round(mixer.getTrackPeaks(self.ColT[m].TrackNum, midi.PEAK_LR_INV) * self.MeterMax))
                for m in range(0, len(self.ColT) - 1):
                    self.ColT[m].Peak = max(0, round(mixer.getTrackPeaks(self.ColT[m].TrackNum, 0) * self.MeterMax))
                n = max(0, round(mixer.getTrackPeaks(MasterPeak, 0) * self.MeterMax))
                device.midiOutSysex(bytes(bytearray([0xd1, n, 0xF7])))
                n = max(0, round(mixer.getTrackPeaks(MasterPeak, 1) * self.MeterMax))
                device.midiOutSysex(bytes(bytearray([0xd1, n+16, 0xF7])))

    #############################################################################################################################
    #                                                                                                                           #
    #  CALLED BY FL WHENEVER IT IS NOT BUSY \\:-)                                                                               #
    #                                                                                                                           #
    #############################################################################################################################
    def OnIdle(self):
        # ----------------
        # REFRESH METERS
        # ---------------
        if device.isAssigned():
            f = self.Page == MackieCUPage_Free
            for m in range(0,  len(self.ColT) - 1):
                self.ColT[m].Tag = utils.Limited(
                    self.ColT[m].Peak, 0, self.MeterMax)
                self.ColT[m].Peak = 0
                if self.ColT[m].Tag == 0:
                    if self.ColT[m].ZPeak:
                        continue
                    else:
                        self.ColT[m].ZPeak = True
                else:
                    self.ColT[m].ZPeak = f
                device.midiOutMsg(midi.MIDI_CHANAFTERTOUCH + (self.ColT[m].Tag << 8) + (m << 12))

        # -------------------------
        # UPDATE THE TIME DISPLAY
        # -------------------------
        n=device.dispatchReceiverCount()+1
        if ui.getTimeDispMin():
            # HHH.MM.SS.CC_
            if playlist.getVisTimeBar() == -midi.MaxInt:
                s = '-   0'
            else:
                h, m = utils.DivModU(n, 60)
                if BankNoInTimeWindow: #loose ticks for readability
                    bank = str(math.ceil(int(self.ColT[m].TrackNum)/n)).zfill(3)
                    s = utils.Zeros_Strict((h * 100 + m) * utils.SignOf(playlist.getVisTimeBar()), 5, ' ')
                    s = s + utils.Zeros_Strict(abs(playlist.getVisTimeStep()), 2)  + bank             
                else:    
                    s = utils.Zeros_Strict((h * 100 + m) * utils.SignOf(playlist.getVisTimeBar()), 5, ' ')
                    s = s + utils.Zeros_Strict(abs(playlist.getVisTimeStep()), 2) + utils.Zeros_Strict(playlist.getVisTimeTick(), 2) + ' '               
        else:
            # BBB.BB.__.TTT
            if BankNoInTimeWindow:
                bank = str(math.ceil(int(self.ColT[m].TrackNum)/n)).zfill(3)
                s = utils.Zeros_Strict(playlist.getVisTimeBar(), 3, ' ') + utils.Zeros_Strict(abs(playlist.getVisTimeStep()), 2) + '  ' + bank 
            else:
                s = utils.Zeros_Strict(playlist.getVisTimeBar(), 3, ' ') + utils.Zeros_Strict(abs(playlist.getVisTimeStep()), 2) + '  ' + utils.Zeros_Strict(playlist.getVisTimeTick(), 3)
        # -------------------------------
        # MANAGE ANY TEMPORARY MESSAGES
        # -------------------------------
        if self.TempMsgDirty:
            self.UpdateTempMsg()
            self.TempMsgDirty = False

        if (self.TempMsgCount > 0) & (self.SliderHoldCount <= 0) & (not ui.isInPopupMenu()):
            self.TempMsgCount -= 1
            if self.TempMsgCount == 0:
                self.UpdateTempMsg()
                

    #############################################################################################################################
    #                                                                                                                           #
    #  Called for all MIDI messages that were not handled by OnMidiIn.       .                                                  #
    #                                                                                                                           #
    #############################################################################################################################
    def OnMidiMsg(self, event):
        #  FLC Processing:
        #if (event.data1 >= 0x36 and event.data1<=0x45):
        #    pointer=event.data1-0x36
        #    event.data1=(event.data1+FLC_Mapping[pointer])
        event.data1=MCUELU.get(event.data1,event.data1)
        if ThrottleStickSupport:
            ###################################################
            ## Do something relevant with the Throttle Stick:
            ###################################################
            self.PreviousCommand=event.data1
            if event.data1==0x0:
                if (ui.getFocused(midi.widPlaylist) or (ui.getFocused(midi.widPianoRoll))):  #Zoom in or out of the PlayList
                    ui.horZoom(event.data2-self.LastData2)
                    ui.verZoom(event.data2-self.LastData2)
                    self.LastData2=(event.data2)
                elif  (ui.getFocused(midi.widMixer)): #Raise or lower volume of selected tracks
                    for x in range(0, 24): #mixer.trackCount()):
                        if mixer.isTrackEnabled(x):
                            mixer.setTrackVolume(x,mixer.getTrackVolume(x)+((event.data2-64)/264))  #I think we can improve on this algorythm?


        #############################################################################################################################
        #                                                                                                                           #
        #   CONTROL CHANGE                                                                                                          #
        #                                                                                                                           #
        #############################################################################################################################
        if (event.midiId == midi.MIDI_CONTROLCHANGE):
            if (event.midiChan == 0):
                event.inEv = event.data2
                if event.inEv >= 0x40:
                    event.outEv = -(event.inEv - 0x40)
                else:
                    event.outEv = event.inEv
                   
                if event.data1 == 0x3C:             
                    event.handled = True

                # knobs
                elif event.data1 in [0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17]:
                    r = utils.KnobAccelToRes2(event.outEv)  # todo outev signof
                    Res = r * (1 / (40 * 2.5))
                    if self.Page == MackieCUPage_FX:
                        self.SetKnobValue(event.data1 - 0x10, event.outEv, Res)
                        event.handled = True
                    if self.Page == MackieCUPage_Free:
                        i = event.data1 - 0x10
                        self.ColT[i].Peak = self.ActivityMax
                        event.data1 = self.ColT[i].BaseEventID + \
                            int(self.ColT[i].KnobHeld)
                        event.isIncrement = 1
                        s = chr(0x7E + int(event.outEv < 0))
                        self.SendMsg2('Free knob ' + str(event.data1) + ': ' + s)
                        device.processMIDICC(event)
                        device.hardwareRefreshMixerTrack(self.ColT[i].TrackNum)
                    else:
                        self.SetKnobValue(event.data1 - 0x10, event.outEv, Res)
                        event.handled = True
                else:
                    event.handled = False  # for extra CCs in emulators
            else:
                event.handled = False  # for extra CCs in emulators

        #############################################################################################################################
        #                                                                                                                           #
        #   PITCH BEND (FADERS)                                                                                                     #
        #                                                                                                                           #
        #############################################################################################################################
        elif event.midiId == midi.MIDI_PITCHBEND:
            if event.midiChan <= 8:
                event.inEv = event.data1 + (event.data2 << 7)
                event.outEv = (event.inEv << 16) // 16383
                event.inEv -= 0x2000

                if self.Page == MackieCUPage_Free:
                    self.ColT[event.midiChan].Peak = self.ActivityMax
                    self.FreeCtrlT[self.ColT[event.midiChan].TrackNum] = event.data1 + \
                        (event.data2 << 7)
                    device.hardwareRefreshMixerTrack(
                        self.ColT[event.midiChan].TrackNum)
                    event.data1 = self.ColT[event.midiChan].BaseEventID + 7
                    event.midiChan = 0
                    event.midiChanEx = event.midiChanEx & (not 0xF)
                    self.SendMsg2('Free slider ' + str(event.data1) + ': ' +
                                  ui.getHintValue(event.outEv, midi.FromMIDI_Max))
                    device.processMIDICC(event)
                elif self.ColT[event.midiChan].SliderEventID >= 0:
                    # slider (mixer track volume)
                    if self.ColT[event.midiChan].TrackNum >= 0:
                        if (self.Page != MackieCUPage_EQ) and (self.Page != MackieCUPage_FX):
                            if (TouchFaderToSelect):                       
                                if mixer.trackNumber != self.ColT[event.midiChan].TrackNum:
                                    mixer.setTrackNumber(self.ColT[event.midiChan].TrackNum)
                    event.handled = True
                    mixer.automateEvent(self.ColT[event.midiChan].SliderEventID, self.AlphaTrack_SliderToLevel(
                        event.inEv + 0x2000), midi.REC_MIDIController, self.SmoothSpeed)
                    # hint
                    n = mixer.getAutoSmoothEventValue(
                        self.ColT[event.midiChan].SliderEventID)
                    s = mixer.getEventIDValueString(
                        self.ColT[event.midiChan].SliderEventID, n)
                    if s != '':
                        s = ': ' + s
                    self.SendMsg2(self.ColT[event.midiChan].SliderName + s)

        #############################################################################################################################
        #                                                                                                                           #
        #   MIDI NOTEON/OFF                                                                                                         #
        #                                                                                                                           #
        #############################################################################################################################
        elif (event.midiId == midi.MIDI_NOTEON) | (event.midiId == midi.MIDI_NOTEOFF):  # NOTE

            if event.midiId == midi.MIDI_NOTEON:
                if event.data2 > 0:
                    if event.data1 in [0x68, 0x69, 0x70]:
                        self.SliderHoldCount += -1 + (int(event.data2 > 0) * 2)

                    # -----------
                    # Piano Roll
                    # -----------
                    if event.data1 == 0x90: 
                        if ui.getVisible(midi.widPianoRoll):
                            ui.hideWindow(midi.widPianoRoll)
                            self.SendMsg2("The Piano Roll Window is Closed")
                        else:
                            ui.showWindow(midi.widPianoRoll)
                            ui.setFocused(midi.widPianoRoll)
                            self.SendMsg2("The Piano Roll is Open")

                    # -----------------
                    # Hide all Windows
                    # -----------------
                    if event.data1 == 0x91: 
                        for x in range(0, 5):
                            ui.hideWindow(x)


                    # --------------
                    # Playlist
                    # --------------
                    if event.data1 == 0x92: 
                        if ui.getVisible(midi.widPlaylist):
                            ui.hideWindow(midi.widPlaylist)
                            self.SendMsg2("The PlayList/Song Window is Closed")
                        else:
                            ui.showWindow(midi.widPlaylist)
                            ui.setFocused(midi.widPlaylist)
                            self.SendMsg2("The Playlist/Song Window is Open")

                    # -------
                    # MIXER
                    # -------
                    elif event.data1 == 0x3F:  # Mixer
                        if self.Shift:
                            if self.ShowTrackNumbers:
                                self.ShowTrackNumbers = False
                            else:
                                self.ShowTrackNumbers = True
                            self.UpdateTextDisplay()
                        else:
                            if ui.getVisible(midi.widMixer):
                                ui.hideWindow(midi.widMixer)
                                self.SendMsg2("The Mixer Window is Closed")
                            else:
                                ui.showWindow(midi.widMixer)
                                ui.setFocused(midi.widMixer)
                                self.SendMsg2("The Mixer Window is Open")
                    # ---------
                    # CHANNEL
                    # --------
                    elif event.data1 == 0x40:  # Channel Rack
                        if self.Shift:
                            if ui.getFocused(5) == 0:
                                channels.focusEditor(channels.getChannelIndex(
                                    channels.selectedChannel()))
                                channels.showCSForm(channels.getChannelIndex(
                                    channels.selectedChannel(-1)))
                            else:
                                channels.focusEditor(channels.getChannelIndex(
                                    channels.selectedChannel()))
                                channels.showCSForm(channels.getChannelIndex(
                                    channels.selectedChannel(-1)), 0)
                        else:
                            if ui.getVisible(midi.widChannelRack):
                                ui.hideWindow(midi.widChannelRack)
                                self.SendMsg2("The Channel Rack Window is Closed")
                            else:
                                ui.showWindow(midi.widChannelRack)
                                ui.setFocused(midi.widChannelRack)
                                self.SendMsg2("The Channel Rack Window is Open")
                    # -------
                    # TEMPO
                    # -------
                    elif event.data1 == 0x41:
                        transport.globalTransport(midi.FPT_TapTempo, 1)
                        s = str(mixer.getCurrentTempo(True))[:-2]
                        self.SendMsg2("Tempo: "+s)
                    # --------
                    # WINDOW
                    # --------
                    elif event.data1 == 0x4c:
                        ui.nextWindow()
                        s = ui.getFocusedFormCaption()
                        if s != "":
                            self.SendMsg2('Current window: ' + s)

                if (event.pmeFlags & midi.PME_System != 0):
                    # ---------------
                    # MODE (METERS)
                    # ---------------
                    if event.data1 == 0x34:
                        if event.data2 > 0:                           
                            if self.Shift:
                                self.FirstTrackT[self.FirstTrack] = 1
                                self.SetPage(self.Page)
                                self.SendMsg2(
                                    'Extender on ' + self.MackieCU_ExtenderPosT[self.ExtenderPos], 1500)
                            else:                             
                                self.MeterMode = (self.MeterMode + 1) % 3
                                self.SendMsg2(self.MackieCU_MeterModeNameT[self.MeterMode])
                                self.ShowSelectedTrackInTimeWindow=(self.MeterMode==2) #Selected Track
                                self.UpdateMeterMode()
                                device.dispatch(0, midi.MIDI_NOTEON + (event.data1 << 8) + (event.data2 << 16))
                                device.midiOutSysex(bytes(bytearray([0xd1, 0, 0xF7])))
                                device.midiOutSysex(bytes(bytearray([0xd1, 16, 0xF7])))
                    # -------------------------------
                    # BANK UP / DOWN (8/16 - 24 tracks is static?)
                    # -------------------------------
                    elif (event.data1 == 0x2E) | (event.data1 == 0x2F):  # mixer bank
                        if event.data2 > 0:
                            n=device.dispatchReceiverCount()
                            if (n>1):
                                self.SendMsg2("Banking is not supported over more than 16 tracks")
                            else:
                                self.SetFirstTrack(self.FirstTrackT[self.FirstTrack] - 8 + int(event.data1 == 0x2F) * 16)
                                device.dispatch(0, midi.MIDI_NOTEON + (event.data1 << 8) + (event.data2 << 16))
                                for m in range(0,  n):
                                    self.SetFirstTrack(self.FirstTrackT[self.FirstTrack] - 8 + int(event.data1 == 0x2F) * 16)
                                    device.dispatch(0, midi.MIDI_NOTEON + (event.data1 << 8) + (event.data2 << 16))
                             
                                if self.MixerScroll:
                                    if self.ColT[event.midiChan].TrackNum >= 0:
                                        if mixer.trackNumber != self.ColT[event.midiChan].TrackNum:
                                            mixer.setTrackNumber(self.ColT[event.midiChan].TrackNum+(-1), midi.curfxScrollToMakeVisible | midi.curfxMinimalLatencyUpdate)

                            if (self.CurPluginID != -1):  # Selected Plugin
                                if (event.data1 == 0x2E) & (self.PluginParamOffset >= 8):
                                    self.PluginParamOffset -= 8
                                elif (event.data1 == 0x2F) & (self.PluginParamOffset + 8 < plugins.getParamCount(mixer.trackNumber(), self.CurPluginID + self.CurPluginOffset) - 8):
                                    self.PluginParamOffset += 8
                            else:  # No Selected Plugin
                                if (event.data1 == 0x2E) & (self.CurPluginOffset >= 2):
                                    self.CurPluginOffset -= 2
                                elif (event.data1 == 0x2F) & (self.CurPluginOffset < 2):
                                    self.CurPluginOffset += 2

                    # ---------------------------
                    # MOVE UP / DOWN (1 track)
                    # ---------------------------
                    elif (event.data1 == 0x30) | (event.data1 == 0x31):
                        if event.data2 > 0:
                            n=device.dispatchReceiverCount()
                            if (n>1):
                                self.SendMsg2("Banking is not supported over more than 16 tracks")
                            else:
                                self.SetFirstTrack(self.FirstTrackT[self.FirstTrack] - 1 + int(event.data1 == 0x31) * 2)
                                device.dispatch(0, midi.MIDI_NOTEON + (event.data1 << 8) + (event.data2 << 16))

                    # ---------------------
                    # FLIP FADERS & VPOTS
                    # ---------------------
                    elif event.data1 == 0x32:  # self.Flip
                        print('D1: ' + str(event.data1) + ' D2: ' + str(event.data2))
                        if event.data2 > 0:
                            self.Flip = not self.Flip
                            device.dispatch(0, midi.MIDI_NOTEON +
                                            (event.data1 << 8) + (event.data2 << 16))
                            self.UpdateColT()
                            self.UpdateLEDs()
                        print('_Flip: ' + str(self.Flip))
                    # ------------
                    # VPOT PUSH
                    # ------------
                    elif event.data1 in [0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27]:
                        if self.Page == MackieCUPage_Free:
                            i = event.data1 - 0x20
                            self.ColT[i].KnobHeld = event.data2 > 0
                            if event.data2 > 0:
                                self.ColT[i].Peak = self.ActivityMax
                                event.data1 = self.ColT[i].BaseEventID + 2
                                event.outEv = 0
                                event.isIncrement = 2
                                self.SendMsg2(
                                    'Free knob switch ' + str(event.data1))
                                device.processMIDICC(event)
                            device.hardwareRefreshMixerTrack(
                                self.ColT[i].TrackNum)
                            return
                        elif event.data2 > 0:
                            n = event.data1 - 0x20
                            if self.Page == MackieCUPage_Sends:
                                if mixer.setRouteTo(mixer.trackNumber(), self.ColT[n].TrackNum, -1) < 0:
                                    self.SendMsg2('Cannot send to this track')
                                else:
                                    if mixer.getRouteSendActive(mixer.trackNumber(), self.ColT[n].TrackNum):
                                        self.SendMsg2(
                                            "VPOT set for send to " + mixer.getTrackName(self.ColT[n].TrackNum))
                                    else:
                                        self.SendMsg2(
                                            "The "+mixer.getTrackName(self.ColT[n].TrackNum)+" VPOT has been reset")
                                    mixer.afterRoutingChanged()
                            else:
                                if self.Page == MackieCUPage_EQ:
                                    if event.data1 == 0x27:  # "Reset All"
                                        self.SetKnobValue(0, midi.MaxInt)
                                        self.SetKnobValue(1, midi.MaxInt)
                                        self.SetKnobValue(2, midi.MaxInt)
                                        self.SetKnobValue(3, midi.MaxInt)
                                        self.SetKnobValue(4, midi.MaxInt)
                                        self.SetKnobValue(5, midi.MaxInt)
                                        self.SetKnobValue(6, midi.MaxInt)
                                        self.SetKnobValue(7, midi.MaxInt)
                                        SendMsg2("All EQ levels reset")
                                else:
                                    self.SetKnobValue(n, midi.MaxInt)
                                    # if self.Page == MackieCUPage_FX:
                                    #SendMsg2("\\ Pending Functionality! \\ "+self.ColT[n].TrackName)
                    # -------------------
                    # FREE HOLD BUTTONS
                    # -------------------
                    elif (event.data1 >= 0) & (event.data1 <= 0x1F):
                        if self.Page == MackieCUPage_Free:
                            i = event.data1 % 8
                            self.ColT[i].Peak = self.ActivityMax
                            event.data1 = self.ColT[i].BaseEventID + \
                                3 + event.data1 // 8
                            event.inEv = event.data2
                            event.outEv = int(event.inEv > 0) * \
                                midi.FromMIDI_Max
                            self.SendMsg2('Free button ' + str(event.data1) +
                                          ': ' + OffOnStr[event.outEv > 0])
                            device.processMIDICC(event)
                            device.hardwareRefreshMixerTrack(
                                self.ColT[i].TrackNum)
                            return

                if (event.pmeFlags & midi.PME_System_Safe != 0):              
                    if False:  #for script compatibility with extender
                        0+1
                    # --------
                    # SELECT
                    # --------
                    elif (event.data1 >= 0x18) & (event.data1 <= 0x1F):
                        if event.data2 > 0:
                            i = event.data1 - 0x18

                            ui.showWindow(midi.widMixer)
                            ui.setFocused(midi.widMixer)
                            self.UpdateLEDs()
                            mixer.setTrackNumber(
                                self.ColT[i].TrackNum, midi.curfxScrollToMakeVisible | midi.curfxMinimalLatencyUpdate)

                            if self.Control:  # Link channel to track
                                mixer.linkTrackToChannel(midi.ROUTE_ToThis)
                            # Show Full Trackname on second display:
                            # EXPAND WITH CONTEXT?
                            SendMsg2(mixer.getTrackName(self.ColT[i].TrackNum))

                    # ------
                    # SOLO
                    # ------
                    elif (event.data1 >= 0x8) & (event.data1 <= 0xF):  # solo
                        if event.data2 > 0:
                            i = event.data1 - 0x8
                            self.ColT[i].solomode = midi.fxSoloModeWithDestTracks
                            if self.Shift:
                                Include(self.ColT[i].solomode,midi.fxSoloModeWithSourceTracks)
                            mixer.soloTrack(self.ColT[i].TrackNum,
                                            midi.fxSoloToggle, self.ColT[i].solomode)
                            mixer.setTrackNumber(
                                self.ColT[i].TrackNum, midi.curfxScrollToMakeVisible)

                    # ------
                    # MUTE
                    # ------
                    elif (event.data1 >= 0x10) & (event.data1 <= 0x17):  # mute
                        if event.data2 > 0:
                            mixer.enableTrack(
                                self.ColT[event.data1 - 0x10].TrackNum)

                    elif (event.data1 >= 0x0) & (event.data1 <= 0x7):  # arm
                        if event.data2 > 0:
                            mixer.armTrack(self.ColT[event.data1].TrackNum)
                            if mixer.isTrackArmed(self.ColT[event.data1].TrackNum):
                                self.SendMsg2(mixer.getTrackName(
                                    self.ColT[event.data1].TrackNum) + ' recording to ' + mixer.getTrackRecordingFileName(self.ColT[event.data1].TrackNum), 2500)
                            else:
                                self.SendMsg2(mixer.getTrackName(
                                    self.ColT[event.data1].TrackNum) + ' unarmed')
                    # ------
                    # SAVE
                    # ------
                    elif event.data1 == 0x50:  # save/save new
                        transport.globalTransport(
                            midi.FPT_Save + int(self.Shift), int(event.data2 > 0) * 2, event.pmeFlags)
                    event.handled = True
                else:
                    event.handled = False
            else:
                event.handled = False

    #############################################################################################################################
    #                                                                                                                           #
    #  HANDLES KNOB FUNCTIONS                                                                                                   #
    #                                                                                                                           #
    #############################################################################################################################

    def SetKnobValue(self, Num, Value, Res=midi.EKRes):
        print('SetKnobValue')

        if (self.ColT[Num].KnobEventID >= 0) & (self.ColT[Num].KnobMode < 4):
            if Value == midi.MaxInt:
                if self.Page == MackieCUPage_FX:
                    if self.ColT[Num].KnobPressEventID >= 0:
                        Value = channels.incEventValue(self.ColT[Num].KnobPressEventID, 0, midi.EKRes)
                        channels.processRECEvent(self.ColT[Num].KnobPressEventID, Value, midi.REC_Controller)
                        s = mixer.getEventIDName(self.ColT[Num].KnobPressEventID)
                        self.SendMsg2("CH"+str(mixer.trackNumber()).zfill(2)+" - "+mixer.getTrackName(mixer.trackNumber())+" ("+self.ColT[Num].TrackName+")".ljust(56, ' '))
                    self.CurPluginID = Num
                    self.PluginParamOffset = 0
                    self.UpdateColT()
                    self.UpdateLEDs()
                    self.UpdateTextDisplay()
                    return
                else:
                    mixer.automateEvent(
                        self.ColT[Num].KnobResetEventID, self.ColT[Num].KnobResetValue, midi.REC_MIDIController, self.SmoothSpeed)
            else:
                mixer.automateEvent(
                    self.ColT[Num].KnobEventID, Value, midi.REC_Controller, self.SmoothSpeed, 1, Res)
            # hint
            n = mixer.getAutoSmoothEventValue(self.ColT[Num].KnobEventID)
            s = mixer.getEventIDValueString(self.ColT[Num].KnobEventID, n)
            if s != '':
                s = ': ' + s
            #self.SendMsg2((self.ColT[Num].KnobName + s).ljust(56, ' '))
            self.SendMsg2(self.ColT[Num].KnobName + s)
        #mixer.automateEvent(self.ColT[Num].KnobEventID, Value, midi.REC_Controller, self.SmoothSpeed, 1, Res)

# -------------------------------------------------------------------------------------------------------------------------------
# PROCEDURES
# -------------------------------------------------------------------------------------------------------------------------------
    #############################################################################################################################
    #                                                                                                                           #
    #   SEND A MESSAGE TO A DISPLAY                                                                                     #
    #                                                                                                                           #
    #############################################################################################################################

    def SendMsg(self, Msg, Row=0, Display=1):
        print('SendMsg')

        #Msg=Msg.rstrip()
        if Display == 1:
            if (EMAGIC):
                sysex = EMAGIC_LCD1 + bytearray(Msg, 'utf-8')
            else: 
                sysex = self.LCD1 + bytearray(Msg, 'utf-8') 
            sysex.append(0xF7)
            device.midiOutSysex(bytes(sysex))
    
        elif Display == 2:
            if (TargetSecondDisplays):
                sysex = self.LCD2 + bytearray(Msg, 'utf-8')
                sysex.append(0xF7)
                device.midiOutSysex(bytes(sysex))
            elif (RouteTempTextToClassic):
               #sysex = self.LCD1 + bytearray(Msg[0:56].rstrip(), 'utf-8')
               sysex = self.LCD1 + bytearray(Msg, 'utf-8')
               sysex.append(0xF7)
               device.midiOutSysex(bytes(sysex))
        elif Display == 3:
            ui.setHintMsg(Msg)
            

    #############################################################################################################################
    #                                                                                                                           #
    #   SEND A SECONDARY MESSAGE                                                                                                #
    #                                                                                                                           #
    #############################################################################################################################
    def SendMsg2(self, Msg, Duration=500):
        print('SendMsg2')

        #Msg=Msg.rstrip()
        if len(Msg)>2:
            if (RouteTempTextToFLDisplay):                
                ui.setHintMsg((Msg+' '*56)[0:56])
            if (TargetSecondDisplays):
                self.SendMsg('  '+Msg.ljust(54, ' '), 0, 2)
            elif RouteTempTextToClassic: 
                if SplitAccrossScribbleStrips:
                    self.OnSendTempMsg(self.TidyScribbles(Msg),Duration)
                else:    
                    self.OnSendTempMsg(Msg,Duration)
                
         
    def OnSendTempMsg(self, Msg, Duration = 500):
        print('OnSendTempMsg')

        if RouteTempTextToClassic: 
            self.TempMsgCount = (Duration // 48) + 1
            self.TempMsgT[1] = Msg.ljust(56, ' ')
            self.TempMsgDirty = True
            
    def UpdateTempMsg(self):
        print('UpdateTempMsg')

        if (RouteTempTextToClassic):
            self.SendMsg(self.TempMsgT[int(self.TempMsgCount != 0)],0,2) #todo was sendmsg
            
    #############################################################################################################################
    #                                                                                                                           #
    #  Called for short MIDI out messages sent from MIDI Out plugin.                                                            #
    #                                                                                                                           #
    #############################################################################################################################
    def SendAssignmentMsg(self, Msg):
        print('SendAssignmentMsg')

        s_ansi = Msg + chr(0) #AnsiString(Msg);
        if device.isAssigned():
            for m in range(1, 3):
                device.midiOutMsg(midi.MIDI_CONTROLCHANGE + ((0x4C - m) << 8) + (ord(s_ansi[m]) << 16))            


    #############################################################################################################################
    #                                                                                                                           #
    #  HANDLES PRINCIPAL LOGIC FOR DISPLAYING TRACK DATA ON DISPLAYS / SCRIBBLE STRIPS                                                                 #
    #                                                                                                                           #
    #############################################################################################################################
    def UpdateTextDisplay(self):
        print('UpdateTextDisplay')

        s1 = ''
        s2 = ''
        s3 = ''
        ch = "CH"
        master = 'MASTER '
        SelectedTrack = mixer.trackNumber()-1
        EffectsExist = False
        if self.Page == MackieCUPage_Free:
            ch = "FR"
        elif self.Page == MackieCUPage_FX:
            ch = "FX"
        elif self.Page == MackieCUPage_EQ:
            ch = "EQ"
        for m in range(0, len(self.ColT) - 1):
            s = ''
            sa = ''
            sa2 = ''
            if self.Page == MackieCUPage_Free:
                s = '  ' + utils.Zeros(self.ColT[m].TrackNum + 1, 2, ' ')
                ch = "FR"
                master = "FR08   "
            elif self.Page == MackieCUPage_FX and self.CurPluginID == -1:
                ch = "FX"
                master = "FX08   "
                if plugins.isValid(mixer.trackNumber(), m):
                    EffectsExist = True
                    #s = DisplayName(plugins.getPluginName(self.ColT[m].TrackNum,m))
                    t = (plugins.getPluginName(mixer.trackNumber(), m)).split()
                    s = t[0][0:6]
                    if len(t) == 3:
                        # otherwise we can miss important aspects of the plugin like version number
                        t[1] = t[1]+t[2]
                    if len(t) >= 2:
                        sa = t[1][0:6].title()
                    elif (len(t) == 1 and len(t[0]) > 6):
                        sa = t[0][6:]
                        if len(sa) == 1:  # This just looks ugly so instead:
                            s = t[0][0:5]
                            sa = t[0][5:]
                    else:
                        sa = "       "
                else:
                    s = "   \\   "  # invalid
                    sa = "   \\   "
                if self.ColT[m].TrackNum > 99:
                    sa2 = ch[1]+str(self.ColT[m].TrackNum).zfill(2)+'   '
                else:
                    sa2 = 'ch'+str(self.ColT[m].TrackNum).zfill(2)+'   '
            elif self.Page == MackieCUPage_FX and self.CurPluginID > -1:  # plugin params
                t = self.ColT[m].TrackName.split()
                if len(t) > 0:
                    s = t[0][0:6]
                    if len(t) == 3:
                        # otherwise we can miss important aspects of the param
                        t[1] = t[1]+t[2]
                    if len(t) >= 2:
                        sa = t[1][0:6].title()
                    elif (len(t) == 1 and len(t[0]) > 6):
                        sa = t[0][6:]
                        if len(sa) == 1:  # This just looks ugly so instead:
                            s = t[0][0:5]
                            sa = t[0][5:]
                    else:
                        sa = "       "
                else:
                    s = "      "
                    sa = "      "
            elif ((self.Page == MackieCUPage_Pan) or (self.Page == MackieCUPage_Sends) or (self.Page == MackieCUPage_Stereo)):
                if self.ShowTrackNumbers:
                    s = mixer.getTrackName(self.ColT[m].TrackNum, 6)
                    sa = '   '+str(self.ColT[m].TrackNum)+' '
                else:
                    t = mixer.getTrackName(self.ColT[m].TrackNum, 12).split()
                    if len(t) > 0:
                        s = t[0][0:6]
                        if len(t) == 3:
                            # otherwise we can miss important aspects of the name
                            t[1] = t[1]+t[2]
                        if len(t) >= 2:
                            sa = t[1][0:6].title()
                        elif (len(t) == 1 and len(t[0]) > 6):
                            sa = t[0][6:]
                            # This just looks ugly so instead:
                            if len(sa) == 1:
                                s = t[0][0:5]
                                sa = t[0][5:]
                        else:
                            sa = "       "
                    else:
                        s = "      "
                        sa = "      "
            # Now do everything outside that loop:
            if ((self.Page == MackieCUPage_Pan) or (self.Page == MackieCUPage_Sends) or (self.Page == MackieCUPage_Stereo) or (self.Page == MackieCUPage_FX)):
                if self.ColT[m].TrackNum > 99:
                    sa2 = ch[1]+str(self.ColT[m].TrackNum).zfill(2)+'   '
                else:
                    sa2 = ch+str(self.ColT[m].TrackNum).zfill(2)+'   '
                for n in range(1, 7 - len(s) + 1):
                    s = s + ' '
                for n in range(1, 7 - len(sa) + 1):
                    sa = sa + ' '
                s1 = s1 + s
                s2 = s2 + sa
                s3 = s3 + sa2
            elif self.Page == MackieCUPage_Free:
                if self.FreeText == 0:
                    # Good for all (most) Roland Zenology Instruments
                    self.SendMsg2("(Zenology Instruments)")
                    s2 = "Cutoff  Reso   Attack Release Vibrato Decay Sust  Level"
                elif self.FreeText == 1:
                    self.SendMsg2("(Common Synth Parameters)")
                    s2 = "Cutoff  Reso   Attack  Decay  Sustain Release Vib Level"
                elif self.FreeText == 2:
                    self.SendMsg2("(Generic Parameters)")
                    s2 = "Param1 Param2 Param3 Param4 Param5 Param6 Param7 Param8"
                else:
                    self.SendMsg2("Blank")
                    s2 = "                                                       "  # Or maybe just blank?
            elif self.Page == MackieCUPage_EQ:
                s1 = "  Low    Med    High   Low    Med   High           Reset"
                s2 = "  Freq   Freq   Freq   Width  Width Width           All "                
        s3=" "*56+s3       
        self.SendMsg(s1+s2,0,1)
        n=device.dispatchReceiverCount()+1
        if (AlwaysShowSelectedTrack):
            self.SendAssignmentMsg(str(mixer.trackNumber()).zfill(3))
#        self.SendMsg2(s3[0:112] + 'BNK'+str(math.ceil(self.ColT[m].TrackNum/(8*n))).zfill(2))
        if RouteTempTextToClassic:
            self.TempMsgT[0] = s1[0:56]
            if self.TempMsgCount == 0:
                self.UpdateTempMsg()
            else:
                self.SendMsg(s1[0:56], 1)
        if TargetSecondDisplays:
            self.SendMsg2(s3[0:112] + 'BNK'+str(math.ceil(self.ColT[m].TrackNum/(8*n))).zfill(2))


    #############################################################################################################################
    #                                                                                                                           #
    #  HANDLES UPDATING OF CHANNEL STRIPS FOR ASSIGNMENT SENDS, FX AND FREE                                                     #
    #                                                                                                                           #
    #############################################################################################################################

    def UpdateMixer_Sel(self):
        print('UpdateMixer_Sel')


        if self.Page != MackieCUPage_Free:
            if device.isAssigned():
                for m in range(0, len(self.ColT) - 1):
                    device.midiOutNewMsg(((0x18 + m) << 8) +
                                         midi.TranzPort_OffOnT[self.ColT[m].TrackNum == mixer.trackNumber()], self.ColT[m].LastValueIndex + 4)

            if self.Page in [MackieCUPage_Sends, MackieCUPage_FX]:
                self.UpdateColT()

    #############################################################################################################################
    #                                                                                                                           #
    #  PRINCIPAL FUNCTION RESPONSIBLE FOR UPDATING COLUMNS                                                                       #
    #                                                                                                                           #
    #############################################################################################################################
    def UpdateCol(self, Num):
        #print('UpdateCol')


        data1 = 0
        data2 = 0
        baseID = 0
        center = 0
        b = False

        if device.isAssigned():
            if self.Page == MackieCUPage_Free:
                baseID = midi.EncodeRemoteControlID(
                    device.getPortNumber(), 0, self.ColT[Num].BaseEventID)
                # slider
                m = self.FreeCtrlT[self.ColT[Num].TrackNum]
                device.midiOutNewMsg(midi.MIDI_PITCHBEND + Num + ((m & 0x7F) << 8) + ((m >> 7) << 16), self.ColT[Num].LastValueIndex + 5)
                if Num < 8:
                    # ring
                    d = mixer.remoteFindEventValue(
                        baseID + int(self.ColT[Num].KnobHeld))
                    if d >= 0:
                        m = 1 + round(d * 10)
                    else:
                        m = int(self.ColT[Num].KnobHeld) * (11 + (2 << 4))
                    device.midiOutNewMsg(midi.MIDI_CONTROLCHANGE + ((0x30 + Num) << 8) + (m << 16), self.ColT[Num].LastValueIndex)
                    # buttons
                    for n in range(0, 4):
                        d = mixer.remoteFindEventValue(baseID + 3 + n)
                        if d >= 0:
                            b = d >= 0.5
                        else:
                            b = False

                        device.midiOutNewMsg(((n * 8 + Num) << 8) + midi.TranzPort_OffOnT[b], self.ColT[Num].LastValueIndex + 1 + n)
            else:
                sv = mixer.getEventValue(self.ColT[Num].SliderEventID)

                if Num < 8:
                    # V-Pot
                    center = self.ColT[Num].KnobCenter
                    if self.ColT[Num].KnobEventID >= 0:
                        m = mixer.getEventValue(
                            self.ColT[Num].KnobEventID, midi.MaxInt, False)
                        if center < 0:
                            if self.ColT[Num].KnobResetEventID == self.ColT[Num].KnobEventID:
                                center = int(
                                    m != self.ColT[Num].KnobResetValue)
                            else:
                                center = int(
                                    sv != self.ColT[Num].KnobResetValue)

                        if self.ColT[Num].KnobMode < 2:
                            data1 = 1 + round(m * (10 / midi.FromMIDI_Max))
                        else:
                            data1 = round(m * (11 / midi.FromMIDI_Max))
                        if self.ColT[Num].KnobMode > 3:
                            data1 = (center << 6)
                        else:
                            data1 = data1 + \
                                (self.ColT[Num].KnobMode << 4) + (center << 6)
                    else:
                        data1 = 0

                        if self.Page == MackieCUPage_FX:
                            # Plugin Parameter Value
                            paramValue = plugins.getParamValue(int(
                                Num + self.PluginParamOffset), mixer.trackNumber(), int(self.CurPluginID + self.CurPluginOffset))
                            data1 = int(paramValue)
                            self.SendMsg2("To Do \\:-) ")
                            # TODO fix when getParamValue starts working

                    device.midiOutNewMsg(
                        midi.MIDI_CONTROLCHANGE + ((0x30 + Num) << 8) + (data1 << 16), self.ColT[Num].LastValueIndex)

                    # arm, solo, mute
                    device.midiOutNewMsg(((0x00 + Num) << 8) + midi.TranzPort_OffOnBlinkT[int(mixer.isTrackArmed(
                        self.ColT[Num].TrackNum)) * (1 + int(transport.isRecording()))], self.ColT[Num].LastValueIndex + 1)
                    device.midiOutNewMsg(((0x08 + Num) << 8) + midi.TranzPort_OffOnT[mixer.isTrackSolo(
                        self.ColT[Num].TrackNum)], self.ColT[Num].LastValueIndex + 2)
                    device.midiOutNewMsg(((0x10 + Num) << 8) + midi.TranzPort_OffOnT[not mixer.isTrackEnabled(
                        self.ColT[Num].TrackNum)], self.ColT[Num].LastValueIndex + 3)

                # slider
                data1 = self.AlphaTrack_LevelToSlider(sv)
                data2 = data1 & 127
                data1 = data1 >> 7
                device.midiOutNewMsg(midi.MIDI_PITCHBEND + Num + (data2 << 8) +
                                     (data1 << 16), self.ColT[Num].LastValueIndex + 5)

            Dirty = False

    #############################################################################################################################
    #                                                                                                                           #
    #  PRINCIPAL PROCEDURE FOR HANDLING INTERNAL COLUMN LIST                                                                    #
    #                                                                                                                           #
    #############################################################################################################################
    def UpdateColT(self):
        print('UpdateColT')


        f = self.FirstTrackT[self.FirstTrack]
        CurID = mixer.getTrackPluginId(mixer.trackNumber(), 0)

        for m in range(0, len(self.ColT)):
            if self.Page == MackieCUPage_Free:
                # free controls
                if m == 8:
                    self.ColT[m].TrackNum = MackieCU_nFreeTracks
                else:
                    self.ColT[m].TrackNum = (f + m) % MackieCU_nFreeTracks

                self.ColT[m].KnobName = 'Knob ' + \
                    str(self.ColT[m].TrackNum + 1)
                self.ColT[m].SliderName = 'Slider ' + \
                    str(self.ColT[m].TrackNum + 1)

                self.ColT[m].BaseEventID = self.FreeEventID + \
                    self.ColT[m].TrackNum * 8  # first virtual CC
            else:
                self.ColT[m].KnobPressEventID = -1
                if CompactDescriptors:
                    ch=""
                else:    
                    ch = 'CH'+str(self.ColT[m].TrackNum).zfill(2) + ' - '

                # mixer
                if m == 8:
                    self.ColT[m].TrackNum = -2
                    self.ColT[m].BaseEventID = midi.REC_MainVol
                    self.ColT[m].SliderEventID = self.ColT[m].BaseEventID
                    self.ColT[m].SliderName = 'Master Volume'
                else:
                    self.ColT[m].TrackNum = midi.TrackNum_Master + \
                        ((f + m) % mixer.trackCount())
                    self.ColT[m].BaseEventID = mixer.getTrackPluginId(
                        self.ColT[m].TrackNum, 0)
                    self.ColT[m].SliderEventID = self.ColT[m].BaseEventID + \
                        midi.REC_Mixer_Vol
                    s = ch+mixer.getTrackName(self.ColT[m].TrackNum)
                    self.ColT[m].SliderName = s + ' - Volume'

                    self.ColT[m].KnobEventID = -1
                    self.ColT[m].KnobResetEventID = -1
                    self.ColT[m].KnobResetValue = midi.FromMIDI_Max >> 1
                    self.ColT[m].KnobName = ''
                    self.ColT[m].KnobMode = 1  # parameter, pan, volume, off
                    self.ColT[m].KnobCenter = -1

                    self.ColT[m].TrackName = ''

                    if self.Page == MackieCUPage_Pan:
                        self.ColT[m].KnobEventID = self.ColT[m].BaseEventID + \
                            midi.REC_Mixer_Pan
                        self.ColT[m].KnobResetEventID = self.ColT[m].KnobEventID
                        self.ColT[m].KnobName = ch+mixer.getTrackName(
                            self.ColT[m].TrackNum) + ' - ' + 'Pan'
                    elif self.Page == MackieCUPage_Stereo:
                        self.ColT[m].KnobEventID = self.ColT[m].BaseEventID + \
                            midi.REC_Mixer_SS
                        self.ColT[m].KnobResetEventID = self.ColT[m].KnobEventID
                        self.ColT[m].KnobName = mixer.getTrackName(
                            self.ColT[m].TrackNum) + ' - ' + 'Separation'
                    elif self.Page == MackieCUPage_Sends:
                        self.ColT[m].KnobEventID = CurID + \
                            midi.REC_Mixer_Send_First + self.ColT[m].TrackNum
                        s = mixer.getEventIDName(self.ColT[m].KnobEventID)
                        self.ColT[m].KnobName = s
                        self.ColT[m].KnobResetValue = round(
                            12800 * midi.FromMIDI_Max / 16000)
                        self.ColT[m].KnobCenter = mixer.getRouteSendActive(
                            mixer.trackNumber(), self.ColT[m].TrackNum)
                        if self.ColT[m].KnobCenter == 0:
                            self.ColT[m].KnobMode = 4
                        else:
                            self.ColT[m].KnobMode = 2
                    elif self.Page == MackieCUPage_FX:
                        if self.CurPluginID == -1:  # Plugin not selected
                            self.ColT[m].CurID = mixer.getTrackPluginId(
                                mixer.trackNumber(), m + self.CurPluginOffset)
                            self.ColT[m].KnobEventID = self.ColT[m].CurID + \
                                midi.REC_Plug_MixLevel
                            s = mixer.getEventIDName(self.ColT[m].KnobEventID)
                            self.ColT[m].KnobName = s
                            self.ColT[m].KnobResetValue = midi.FromMIDI_Max

                            IsValid = mixer.isTrackPluginValid(
                                mixer.trackNumber(), m + self.CurPluginOffset)
                            IsEnabledAuto = mixer.isTrackAutomationEnabled(
                                mixer.trackNumber(), m + self.CurPluginOffset)
                            if IsValid:
                                self.ColT[m].KnobMode = 2
                                self.ColT[m].KnobPressEventID = self.ColT[m].CurID + \
                                    midi.REC_Plug_Mute

                                self.ColT[m].TrackName = plugins.getPluginName(
                                    mixer.trackNumber(), m + self.CurPluginOffset)
                            else:
                                self.ColT[m].KnobMode = 4
                            self.ColT[m].KnobCenter = int(
                                IsValid & IsEnabledAuto)
                        else:  # Plugin selected
                            self.ColT[m].CurID = mixer.getTrackPluginId(
                                mixer.trackNumber(), m + self.CurPluginOffset)
                            if m + self.PluginParamOffset < plugins.getParamCount(mixer.trackNumber(), self.CurPluginID + self.CurPluginOffset):
                                self.ColT[m].TrackName = plugins.getParamName(
                                    m + self.PluginParamOffset, mixer.trackNumber(), self.CurPluginID + self.CurPluginOffset)
                            self.ColT[m].KnobMode = 2
                            self.ColT[m].KnobEventID = self.ColT[m].CurID + \
                                midi.REC_PlugReserved
                    elif self.Page == MackieCUPage_EQ:
                        if m < 3:
                            # gain & freq
                            self.ColT[m].SliderEventID = CurID + \
                                midi.REC_Mixer_EQ_Gain + m
                            self.ColT[m].KnobResetEventID = self.ColT[m].SliderEventID
                            s = mixer.getEventIDName(
                                self.ColT[m].SliderEventID)
                            self.ColT[m].SliderName = s
                            self.ColT[m].KnobEventID = CurID + \
                                midi.REC_Mixer_EQ_Freq + m
                            s = mixer.getEventIDName(self.ColT[m].KnobEventID)
                            self.ColT[m].KnobName = s
                            self.ColT[m].KnobResetValue = midi.FromMIDI_Max >> 1
                            self.ColT[m].KnobCenter = -2
                            self.ColT[m].KnobMode = 0
                        else:
                            if m < 6:
                                # Q
                                self.ColT[m].SliderEventID = CurID + \
                                    midi.REC_Mixer_EQ_Q + m - 3
                                self.ColT[m].KnobResetEventID = self.ColT[m].SliderEventID
                                s = mixer.getEventIDName(
                                    self.ColT[m].SliderEventID)
                                self.ColT[m].SliderName = s
                                self.ColT[m].KnobEventID = self.ColT[m].SliderEventID
                                self.ColT[m].KnobName = self.ColT[m].SliderName
                                self.ColT[m].KnobResetValue = 17500
                                self.ColT[m].KnobCenter = -1
                                self.ColT[m].KnobMode = 2
                            else:
                                self.ColT[m].SliderEventID = -1
                                self.ColT[m].KnobEventID = -1
                                self.ColT[m].KnobMode = 4

                    # self.Flip knob & slider
                    if self.Flip:
                        self.ColT[m].KnobEventID, self.ColT[m].SliderEventID = utils.SwapInt(
                            self.ColT[m].KnobEventID, self.ColT[m].SliderEventID)
                        s = self.ColT[m].SliderName
                        self.ColT[m].SliderName = self.ColT[m].KnobName
                        self.ColT[m].KnobName = s
                        self.ColT[m].KnobMode = 2
                        if not (self.Page in [MackieCUPage_Sends, MackieCUPage_FX, MackieCUPage_EQ]):
                            self.ColT[m].KnobCenter = -1
                            self.ColT[m].KnobResetValue = round(
                                12800 * midi.FromMIDI_Max / 16000)
                            self.ColT[m].KnobResetEventID = self.ColT[m].KnobEventID

            self.ColT[m].LastValueIndex = 48 + m * 6
            self.ColT[m].Peak = 0
            self.ColT[m].ZPeak = False
            self.UpdateCol(m)

    def SetJogSource(self, Value):
        print('SetJogSource')

        self.JogSource = Value

    def OnWaitingForInput(self):
        print('OnWaitingForInput')


        self.SendTimeMsg('..........')

    def UpdateClicking(self):
        print('UpdateClicking')
  # switch self.Clicking for transport buttons

        if device.isAssigned():
            device.midiOutSysex(
                bytes([0xF0, 0x00, 0x00,  0x66, 0x15, 0x0A, int(self.Clicking), 0xF7]))
    # set backlight timeout (0 should switch off immediately, but doesn't really work well)

    def SetBackLight(self, Minutes):
        print('SetBackLight')

        if device.isAssigned():
            device.midiOutSysex(
                bytes([0xF0, 0x00, 0x00,  0x66, 0x15, 0x0B, Minutes, 0xF7]))
    #############################################################################################################################
    #                                                                                                                           #
    #  HANDLES THE DISPLAY METERS                                                                                                #
    #                                                                                                                           #
    #############################################################################################################################

    def UpdateMeterMode(self):
        print('UpdateMeterMode')


        # force vertical (activity) meter mode for free controls self.Page
        if self.Page == MackieCUPage_Free:
            
            self.CurMeterMode = 1
        else:
            self.CurMeterMode = self.MeterMode

        if device.isAssigned():
            # clear peak indicators
            for m in range(0, len(self.ColT) - 1):
                device.midiOutMsg(midi.MIDI_CHANAFTERTOUCH +
                                  (0xF << 8) + (m << 12))
            # disable all meters
            for m in range(0, 8):
                device.midiOutSysex(
                    bytes([0xF0, 0x00, 0x00,  0x66, 0x15, 0x20, m, 0, 0xF7]))

        if self.CurMeterMode > 0:
            self.TempMsgCount = -1
        else:
            self.TempMsgCount = 500 // 48 + 1

        # $D for horizontal, $E for vertical meters
        self.MeterMax = 0xD + int(self.CurMeterMode == 1)
        self.ActivityMax = 0xD - int(self.CurMeterMode == 1) * 6

        if device.isAssigned():
            # device.midiOutSysex(bytes(bytearray([0xd1, 0xD, 0xF7])))
            # device.midiOutSysex(bytes(bytearray([0xd1, 0xD+16, 0xF7])))
            # horizontal/vertical meter mode
            device.midiOutSysex(
                bytes([0xF0, 0x00, 0x00,  0x66, 0x15, 0x21, int(self.CurMeterMode > 0), 0xF7]))

            # enable all meters
            if self.CurMeterMode == 2:
                n = 1
            else:
                n = 1 + 2
            for m in range(0, 8):
                device.midiOutSysex(
                    bytes([0xF0, 0x00, 0x00,  0x66, 0x15, 0x20, m, n, 0xF7]))

    #############################################################################################################################
    #                                                                                                                           #
    #  HANDLES ASSIGNMENT SELECTION (PLUS CRUDE EXTENDER POSITIONING)                                                            #
    #                                                                                                                           #
    #############################################################################################################################

    def SetPage(self, Value):
        print('SetPage: ' + str(Value))

        oldPage = self.Page
        self.Page = Value

        self.FirstTrack = int(self.Page == MackieCUPage_Free)
        receiverCount = device.dispatchReceiverCount()
        if receiverCount == 0:
            self.SetFirstTrack(self.FirstTrackT[self.FirstTrack])
        elif self.Page == oldPage:
            if self.ExtenderPos == ExtenderLeft:
                for n in range(0, receiverCount):
                    device.dispatch(n, midi.MIDI_NOTEON + (0x7F << 8) +
                                    (self.FirstTrackT[self.FirstTrack] + (n * 8) << 16))
                self.SetFirstTrack(
                    self.FirstTrackT[self.FirstTrack] + receiverCount * 8)
            elif self.ExtenderPos == ExtenderRight:
                self.SetFirstTrack(self.FirstTrackT[self.FirstTrack])
                for n in range(0, receiverCount):
                    device.dispatch(n, midi.MIDI_NOTEON + (0x7F << 8) +
                                    (self.FirstTrackT[self.FirstTrack] + ((n + 1) * 8) << 16))

        if self.Page == MackieCUPage_Free:

            BaseID = midi.EncodeRemoteControlID(
                device.getPortNumber(), 0, self.FreeEventID + 7)
            for n in range(0,  len(self.FreeCtrlT)):
                d = mixer.remoteFindEventValue(BaseID + n * 8, 1)
                if d >= 0:
                    self.FreeCtrlT[n] = min(round(d * 16384), 16384)
            # Toggle options for  Free Controls Text
            if self.Shift:
                if self.FreeText == 0:
                    self.FreeText = 1
                elif self.FreeText == 1:
                    self.FreeText = 2
                elif self.FreeText == 2:
                    self.FreeText = -1
                else:
                    self.FreeText = 0

        if (oldPage == MackieCUPage_Free) | (self.Page == MackieCUPage_Free):
            self.UpdateMeterMode()

        self.CurPluginID = -1
        self.CurPluginOffset = 0

        self.UpdateColT()
        self.UpdateLEDs()
        self.UpdateTextDisplay()

    #############################################################################################################################
    #                                                                                                                           #
    #  SETS UP THE FIRST TRACK AFTER TRACK RELATED MOVEMENT OPERATIONS ARE CARRIED OUT                                          #
    #                                                                                                                           #
    #############################################################################################################################
    def SetFirstTrack(self, Value):
        print('SetFirstTrack')


        if self.Page == MackieCUPage_Free:
            self.FirstTrackT[self.FirstTrack] = (
                Value + MackieCU_nFreeTracks) % MackieCU_nFreeTracks
            s = utils.Zeros(self.FirstTrackT[self.FirstTrack] + 1, 2, ' ')
        else:
            self.FirstTrackT[self.FirstTrack] = (
                Value + mixer.trackCount()) % mixer.trackCount()
            s = utils.Zeros(self.FirstTrackT[self.FirstTrack], 2, ' ')
        self.UpdateColT()
        device.hardwareRefreshMixerTrack(-1)


MackieCU = TMackieCU()

#EOF
def OnInit():
    MackieCU.OnInit()


def OnDeInit():
    MackieCU.OnDeInit()


def OnDirtyMixerTrack(SetTrackNum):
    MackieCU.OnDirtyMixerTrack(SetTrackNum)


def OnRefresh(Flags):
    MackieCU.OnRefresh(Flags)


def OnMidiMsg(event):
    MackieCU.OnMidiMsg(event)


def SendMsg2(Msg, Duration=1000):
    MackieCU.SendMsg2(Msg, Duration)

def OnSendTempMsg(Msg, Duration=1000):
    MackieCU.OnSendTempMsg(Msg, Duration)


def OnUpdateBeatIndicator(Value):
    MackieCU.OnUpdateBeatIndicator(Value)


def OnUpdateMeters():
    MackieCU.OnUpdateMeters()


def OnIdle():
    MackieCU.OnIdle()


def OnWaitingForInput():
    MackieCU.OnWaitingForInput()
